### ISSUE TITLE
Release v10.8?

### ISSUE THREAD

**Issue by ghost** [flathub/io.github.markummitchell.Engauge_Digitizer#1]
Hello,
I have released version 10.8. Do I just update the engauge/sources/url and engauge/sources/sha256 entries in the json file? Do you want to do the release? I don't mind adding the flathub releases to the other releases I create for each version. Thanks! Mark

**Comment by nedrichards** [comment]
Yep, that's exactly it. Update the URLs and sha256sums. Then if you've tested already you can push directly to master and it'll build and release automatically or you can make a PR and type a comment that says "bot, build" (without the quotes). That'll do a test build. Ideally it'll report back on progress in the PR but that's being really flaky so you can always see every builds status at https://flathub.org/builds

**Comment by ghost** [comment]
Thanks. It worked great.
