### ISSUE TITLE
Uses 5.10 SDK

### ISSUE THREAD

**Issue by nedrichards** [flathub/io.github.markummitchell.Engauge_Digitizer#2]
I see the manifest uses the KDE 5.10 SDK which is based upon Qt 5.10. This is now out of security support and won't recieve further updates. It'd be good to move to either the 5.9 lts or the newer and fresher 5.11 SDK.

**Comment by ghost** [comment]
I will look into this today. Thanks for the advice.

**Comment by ghost** [comment]
Thanks. I have moved to 5.11.
